name: FlutterFalcon example
"on":
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]
  workflow_dispatch: {}
  schedule:
    - id: flutter-falcon-example-nightly
      cron: "20 04 * * *"
      ref: master
jobs:
  example:
    name: Test package and build Android artifacts
    runs-on: ubuntu-latest
    run: .action-server/tasks/flutter-falcon-example.sh
    timeoutMinutes: 180
