name: red_rect_app
description: Minimal Flutter Falcon test app.
publish_to: 'none'
version: 1.1.4+8

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  package_info_plus: ^8.3.0
  flutter_falcon:
    git:
      url: https://github.com/dxfoso/flutterfalcon.git
      path: flutter_falcon

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
