name: flutter_falcon_example
description: Minimal Flutter Falcon test app.
publish_to: 'none'
version: 2.0.0+89

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_falcon:
    git:
      url: https://github.com/dxfoso/flutterfalcon.git
      ref: 4b81f64081ae10bd5addd9d574b765fd3ab474be
      path: flutter_falcon

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  shared_preferences: ^2.5.3

flutter_falcon:
  required_build_variables:
    - API_BASE_URL
flutter:
  uses-material-design: true
