name: flutter_falcon_example
description: Minimal Flutter Falcon test app.
publish_to: 'none'
version: 2.0.0+55

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_falcon:
    git:
      url: https://github.com/dxfoso/flutterfalcon.git
      ref: bed0ae3
      path: flutter_falcon
  flutter_falcon_android_direct:
    git:
      url: https://github.com/dxfoso/flutterfalcon.git
      ref: bed0ae3
      path: flutter_falcon_android_direct
  flutter_falcon_ios_app_store:
    git:
      url: https://github.com/dxfoso/flutterfalcon.git
      ref: bed0ae3
      path: flutter_falcon_ios_app_store
  flutter_falcon_macos_app_store:
    git:
      url: https://github.com/dxfoso/flutterfalcon.git
      ref: bed0ae3
      path: flutter_falcon_macos_app_store
  flutter_falcon_windows_direct:
    git:
      url: https://github.com/dxfoso/flutterfalcon.git
      ref: bed0ae3
      path: flutter_falcon_windows_direct
  flutter_falcon_linux_flatpak:
    git:
      url: https://github.com/dxfoso/flutterfalcon.git
      ref: bed0ae3
      path: flutter_falcon_linux_flatpak
  flutter_falcon_web_pwa:
    git:
      url: https://github.com/dxfoso/flutterfalcon.git
      ref: bed0ae3
      path: flutter_falcon_web_pwa
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_falcon:
  platforms:
    ios:
      store_listing_id: '0000000000'
    macos:
      store_listing_id: '0000000000'
    windows:
      package_identity: com.example.flutter_falcon_example
    linux:
      store_listing_id: com.example.flutter_falcon_example
    web:
      package_identity: flutter-falcon-example-web

flutter:
  uses-material-design: true
