version: 1
name: FlutterFalcon example
"on":
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]
  workflow_dispatch: {}
  schedule:
    - id: flutter-falcon-example-nightly
      cron: "20 04 * * *"
      ref: master
jobs:
  example:
    name: Test package and build Android artifacts
    required: true
    runsOn: [linux, x64, docker, host]
    executor: host
    run: .cloud-ci/tasks/flutter-falcon-example.sh
    timeoutMinutes: 180
